name: KameraIOS
options:
  bundleIdPrefix: net.adnan120hz
  createIntermediateGroups: true
deploymentTarget:
  iOS: "18.0"
targets:
  KameraIOS:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: KameraIOS
        excludes:
          - "Info.plist"
    info:
      path: KameraIOS/Info.plist
    settings:
      base:
        PRODUCT_NAME: KameraIOS
        PRODUCT_BUNDLE_IDENTIFIER: net.adnan120hz.camera26ios
        MARKETING_VERSION: "2.0.0"
        CURRENT_PROJECT_VERSION: "7"
        SWIFT_VERSION: "5.0"
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: NO
        ENABLE_PREVIEWS: YES
